"""Middleware execution order for CORS.

``add_middleware`` inserts each middleware at position 0, so the *last* one
added is the *outermost* -- it is the first to see a request and the last to
touch the response. CORS is therefore only outermost if it is added last.

In the app it was added second (right after ``TrustedHostMiddleware``), which
made it nearly innermost: ``RequestIDMiddleware``, ``LoggingMiddleware``,
``RateLimitMiddleware``, ``RequestSizeLimitMiddleware``, ``TimingMiddleware``,
``SecurityHeadersMiddleware`` and ``GZipMiddleware`` all wrapped it. The
consequence is that any response generated by one of those outer layers -- a
``429`` from the rate limiter, a ``413`` from the size limiter, a ``400`` from
the host check -- returned without CORS headers, so a browser reported an opaque
CORS failure instead of the real status. Preflight ``OPTIONS`` requests were
also rate-limited and counted against the caller's budget.

These tests assert the order that makes CORS outermost, which lets a rate
limiter or any other guard short-circuit *inside* CORS so its response still
carries the CORS headers.
"""

from __future__ import annotations

import pytest
from httpx import ASGITransport, AsyncClient

from app.main import app


def _make_client() -> AsyncClient:
    return AsyncClient(
        transport=ASGITransport(app=app), base_url="http://test", follow_redirects=True
    )


def _middleware_names() -> list[str]:
    return [m.cls.__name__ for m in app.user_middleware]


def test_cors_middleware_is_registered() -> None:
    assert "CORSMiddleware" in _middleware_names()


def test_cors_middleware_is_outermost() -> None:
    names = _middleware_names()
    assert names.index("CORSMiddleware") == 0, (
        "CORSMiddleware must be added last so it is outermost; current order: "
        f"{names}"
    )


def test_trusted_host_is_still_active() -> None:
    assert "TrustedHostMiddleware" in _middleware_names()


def test_security_and_limits_remain_registered() -> None:
    names = _middleware_names()
    for expected in (
        "RateLimitMiddleware",
        "RequestSizeLimitMiddleware",
        "SecurityHeadersMiddleware",
        "RequestIDMiddleware",
    ):
        assert expected in names


async def test_inner_middleware_error_response_still_carries_cors_headers() -> None:
    """The behavioural proof: an inner layer's own error is readable cross-origin.

    ``TrustedHostMiddleware`` answers a bad ``Host`` header with a bare
    ``400`` and never calls downstream. With CORS registered second it sat
    *inside* the host check, so that 400 had no Access-Control-Allow-Origin and
    the browser reported an opaque CORS failure instead of the 400. CORS is now
    outermost, so it decorates the inner layer's response.
    """
    from app.core.config import settings

    allowed_origin = settings.cors_origins_list[0]
    async with _make_client() as c:
        resp = await c.get(
            "/api/v1/health",
            headers={"Origin": allowed_origin, "Host": "evil.invalid"},
        )
    assert resp.status_code == 400
    assert resp.headers.get("access-control-allow-origin") == allowed_origin


@pytest.mark.asyncio
async def test_preflight_is_answered_by_cors() -> None:
    """A preflight is short-circuited by CORS and returns 200 with CORS headers."""
    from app.core.config import settings

    allowed_origin = settings.cors_origins_list[0]
    async with _make_client() as c:
        resp = await c.options(
            "/api/v1/presentations",
            headers={
                "Origin": allowed_origin,
                "Access-Control-Request-Method": "POST",
            },
        )
    assert resp.status_code == 200
    assert resp.headers.get("access-control-allow-origin") == allowed_origin
    assert "POST" in (resp.headers.get("access-control-allow-methods") or "")
